### ISSUE TITLE
nprocs, nthreads displaying in MB

### ISSUE THREAD

**Issue by StewMH** [HSF/prmon#103]
I have the following prmon output:
```
Time	nprocs	nthreads	wtime	stime	utime	pss	rss	swap	vmem	rchar	read_bytes	wchar	write_bytes	rx_bytes	rx_packets	tx_bytes	tx_packets
1576523936	2	0	0	0	0	5666	7500	0	41168	651766	5222400	351	0	119240	1742	94493	1744
1576523967	3	10	31	4	16	645854	1133956	0	32669000	115241254	549240832	3084919	892928	9512993	137047	8696700	140331
```
and I'd like to see nprocs and nthreads. at a reasonable scale. I tried:
```
prmon_plot.py --input prmon.full.BSRDOtoRAW --xunit 1 --xvar wtime --yvar nthreads,nprocs
```

This seems to come out in MB only:
![PrMon_wtime_vs_nthreads_nprocs](https://user-images.githubusercontent.com/834238/70943693-5e004980-2049-11ea-81c7-2c64751c3a37.png)

**Comment by StewMH** [comment]
Should say this is with prmon 1.1.1

**Comment by amete** [comment]
Hi @StewMH,

Thanks a lot. I believe you'd get what you want by setting the unit of the y-axis to 1, i.e.:

`prmon_plot.py --input prmon.full.BSRDOtoRAW --yunit 1 --xvar wtime --yvar nthreads,nprocs`

This is what I get using this command w/ a dummy input:

![PrMon_wtime_vs_nthreads_nprocs](https://user-images.githubusercontent.com/7428938/70944743-fac7e480-2053-11ea-90d5-58e0e8d4a8e4.png)

The issue probably stems from the fact that the default y-unit is MB (and x-unit is SEC). Maybe we should make those variable dependent. 

Best,
Serhan

**Comment by StewMH** [comment]
ah yes, x and y - PEBKAC. Thanks!
