### ISSUE TITLE
prmon stops gathering metrics

### ISSUE THREAD

**Issue by gdroy** [HSF/prmon#11]
I'm attempting to run prmon (using the following script) on an existing ATLAS payload as an initial test.

```
#!/bin/bash

(
cd /root/ATLAS/rundir

export VO_ATLAS_SW_DIR=/cvmfs/atlas.cern.ch/repo/sw
export ATHENA_PROC_NUMBER=8;
export ATLAS_LOCAL_ROOT_BASE=/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase;
source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh --quiet;
source $AtlasSetup/scripts/asetup.sh Athena,21.0.31,notest --platform x86_64-slc6-gcc62-opt --makeflags="$MAKEFLAGS";
Sim_tf.py --inputEVNTFile=EVNT.13322104._000284.pool.root.1 --maxEvents=1000 --postInclude default:RecJobTransforms/UseFrontier.py --preExec 'EVNTtoHITS:simFlags.SimBarcodeOffset.set_Value_and_Lock(200000)' 'EVNTtoHITS:simFlags.TRTRangeCut=30.0;
simFlags.TightMuonStepping=True' --preInclude EVNTtoHITS:SimulationJobOptions/preInclude.BeamPipeKill.py --skipEvents=0 --firstEvent=2290001 --outputHITSFile=HITS.13322110._003927.pool.root.1 --physicsList=FTFP_BERT_ATL_VALIDATION --randomSeed=2291 --DBRelease=all:current --conditionsTag default:OFLCOND-MC16-SDR-14 --geometryVersion=default:ATLAS-R2-2016-01-00-01_VALIDATION --runNumber=423210 --AMITag=a875 --DataRunNumber=284500 --simulator=ATLFASTII --truthStrategy=MC15aPlus
) &

MYPID=$$
./prmon --pid ${MYPID}

wait
echo "Done"
```

All seems to work well and until we get to the parallel phase when the tool start to produce 0's for all the metrics:

```
 1521110863	29926216	4465862	23351072	0	568325215	24847004	1774543360	22401024	749.94	24.67	13.98	8.53
1521110865	29927240	4469183	23354380	0	568734129	24847004	1774973440	22401024	770.05	24.8	13.98	8.53
1521110868	20148528	3014859	15607184	0	546868043	16035106	1689260544	13406208	532.48	19.72	13.98	8.53
1521110870	0	0	0	0	0	0	0	0	0	0	0	0
1521110872	0	0	0	0	0	0	0	0	0	0	0	0
1521110874	0	0	0	0	0	0	0	0	0	0	0	0
1521110876	0	0	0	0	0	0	0	0	0	0	0	0
1521110878	0	0	0	0	0	0	0	0	0	0	0	0
```

The prmon tool reports the following errors:

```
rename fails: No such file or directory
prmon.json_tmp prmon.json_snapshot
```
If I turn on verbose output by passing "true" to the ReadProcs function I see:

```
rename fails: No such file or directory
prmon.json_tmp prmon.json_snapshot
MemoryMonitor: unable to open pstree pipe!
```

So it appears that it stops being able to create the pstree command, and I'm unsure why. If I restart prmon and point it to the same pid it starts back up again (although I haven't run it to completion so it may reoccur). I may not have built it correctly or have done something else dumb but I'm really not sure why it can't open the pstree pipe and get a list of pids.

Also as a suggestion we could replace ```pstree -A -p pid | tr ...``` with  ```pgrep -P pid``` which give a list of pids (although you do need to call it recursively to get all child pids) without needing to do the more complex parsing (only need to look for newlines).

System Config:
CentOS Linux release 7.4.1708 (Core) 
libgcc-4.8.5-16.el7_4.2.x86_64
gcc-c++-4.8.5-16.el7_4.2.x86_64
gcc-4.8.5-16.el7_4.2.x86_64
rapidjson-devel-1.1.0-2.el7.noarch

**Comment by gdroy** [comment]
In response to my last comment re pstree vs pgrep, pgrep won't work as it doesn't recurse through child pids and only gives on level so that is a non-starter.

**Comment by graeme-a-stewart** [comment]
Hi

`Sim_tf.py` is a single step transform so it should work - `athena` will pop into existence as a child process of the transform and should be monitored. Even for the more complex multi-step transforms the various athenas will still be children of the guiding python process that is the transform, so they should always be found as children.

It is possible for athena to re-exec itself (to save memory) after initialisation, but the PID should stay the same. That seems to be confirmed if re-starting `prmon` starts to work again.

So this is weird and I have no obvious explanation for why it's happening...

I am not sure I can look before next week, I'm afraid. (Maybe a debug mode for prmon would be useful here.)

Cheers

Graeme

**Comment by gdroy** [comment]
Hi @graeme-a-stewart @amete,

Yeah it's confusing to me, if it was the spawning of the new processes I'd expect it to happen immediately but I get 60+ seconds of the multiple ```athena``` processes running ( I can see loads go up and cpu time jumping up) and then the pipe seems to fail. I admit I've got to the limit of my C++ / pipes knowledge as I'm not seeing this can fail:

```
      snprintf(smaps_buffer,64,"pstree -A -p %ld | tr \\- \\\\n",(long)mother_pid);
      FILE* pipe = popen(smaps_buffer, "r");
      if (pipe==0) {
	if (verbose) 
	  std::cerr << "MemoryMonitor: unable to open pstree pipe!" << std::endl;
        return 1;
      }
```
mother_pid shouldn't have changed (especially in my test as the top level script is always there) and I can't see how pstree can fail... and then fail constantly (or why it would work after restarting ```prmon```).

**Comment by graeme-a-stewart** [comment]
Yes, it's very odd - speciality as that code never changed from MemoryMonitor. I will try and take a look, but all day today I am in a workshop.

**Comment by gdroy** [comment]
Okay found the bug, it is only indirectly due to no being able to open the ```pstree``` pipe. What's actually happening is we're running out of file descriptors. The real culprit is line 113 where we don't close ```file3``` so we keep accumulating open files of /proc/pid/stat until we reach 1024 and then can't open the ```pstree``` pipe. Code should be:

```
        snprintf(stat_buffer,64,"/proc/%llu/stat",(unsigned long long)*it);
        FILE *file3 = fopen(stat_buffer,"r");
        if(file3==0) {
          openFails.push_back(std::string(stat_buffer));
        }
        else {
          while(fgets(sbuffer,2048,file3)) {
            tsbuffer = strchr (sbuffer, ')');
            if(sscanf(tsbuffer + 2 , "%*c %*d %*d %*d %*d %*d %*u %*u %*u %*u %*u %80llu %80llu %80llu %80llu", &utime, &stime, &cutime, &cstime)) {
              valuesCPU[0] += utime;
              valuesCPU[1] += stime;
              valuesCPU[2] += cutime;
              valuesCPU[3] += cstime;
            }
          }
          fclose(file3);
        }
```

**Comment by amete** [comment]
Hi @gdroy,

Thanks! That's an oversight on my part, I'll put in the fix shortly.

Best,
Serhan
