### ISSUE TITLE
Add hardware information to the JSON file

### ISSUE THREAD

**Issue by amete** [HSF/prmon#114]
Let me create this issue so that it is not forgotten. The idea is to add some hardware information on the CPU and the GPU (if it exists) into the JSON file. We can simply create a new section, say `hw`, and populate it accordingly.

I think we should agree on what we want to store. On the CPU side we typically have easy access to the following information (also available through `/proc/cpuinfo`):

```
$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                32
On-line CPU(s) list:   0-31
Thread(s) per core:    2
Core(s) per socket:    8
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 62
Model name:            Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz
Stepping:              4
CPU MHz:               1200.036
CPU max MHz:           4000.0000
CPU min MHz:           1200.0000
BogoMIPS:              6623.89
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              25600K
NUMA node0 CPU(s):     0-7,16-23
NUMA node1 CPU(s):     8-15,24-31
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm epb ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear spec_ctrl intel_stibp flush_l1d
``` 

and on the GPU side, since we're currently only supporting NVIDIA we can simply use `nvidia-smi -L` which gives, e.g.:

```
$ nvidia-smi -L
GPU 0: GeForce RTX 2060 (UUID: GPU-XXX)
```

I guess at the bare minimum we want to keep the number of CPUs/GPUs along w/ their model names.

As to how we'd like to do this, I'm completely impartial. One option is to do this directly in `prmon.cpp` outside the monitoring loop. We can either write helper functions to collect this information directly there, or collect them inside the relative plug-ins (e.g. a la `nvidiamon::test_nvidia_smi()`) and pass them on to the main application as we do for the actual metrics (although this might be a bit awkward if we want to collect the hardware information regardless of whether we run the relevant plug-in).

**Comment by graeme-a-stewart** [comment]
I think it would be a good idea to do this per plugin - we can define a `get_hardware()` method that create dictionary items for a hardware section in the JSON file. (Or `{}` is there is nothing relevant from this plugin.)

I think the advantage of doing it this way is that it would respect any enabling/disabling we do of different plugins (#107) and that there's a clear association with the functionality of different plugins.

I would also say we should make this optional - e.g. ATLAS has the pilot gather this information so we probably don't need to repeat it.

**Comment by amete** [comment]
Sounds good @graeme-a-stewart. I'll prepare a prototype that we can use to discuss the implementation details.
