### ISSUE TITLE
The number of threads that is reported by countmon

### ISSUE THREAD

**Issue by amete** [HSF/prmon#121]
Now when we're counting the number of processes and threads in `countmon`, we offset the mother thread from number of threads, i.e.:

https://github.com/HSF/prmon/blob/5af921b643971300b287d30680318c9383d5ec81/package/src/countmon.cpp#L40-L41

The rationale behind this was to keep track of threads that are explicitly created in each process but I don't think we ever discussed/agreed on this choice. What do you think @graeme-a-stewart? Shall we leave as it's or simply report what we read?

**Comment by graeme-a-stewart** [comment]
I have to say that I never realised we did that. It seems wrong to me to do so, as we have no way of guessing that -1 is an offset that users would want to see (it's also oddly inconsistent with processes, if one thinks of AthenaMP vs. AthenaMT).

I would favour removing this offset and we report what we find.
