### ISSUE TITLE
Contribution and coding guide

### ISSUE THREAD

**Issue by graeme-a-stewart** [HSF/prmon#127]
We should add a contribution guide to the project encouraging other people. I think two things in particular we need

- A description of how to add a new monitoring component
- A code style guide

For the latter I looked at `clang-format` and all of the standard styles look pretty decent to me. I think we used the Google setup in the past, though probably our last PRs deviated from that a bit.

We could also add a CI job to check code formatting.

**Comment by amete** [comment]
That's a good idea. While we're at it, I guess it wouldn't hurt to add a code of conduct, too. 

Actually for the integration, I was wondering if we can switch to using Actions, now? I've been meaning to look into it, but it seems as if there are a lot of things that can be streamlined nowadays: https://github.com/marketplace?type=actions. It seems to be free for public repositories if I understand correctly.

-s

**Comment by graeme-a-stewart** [comment]
👍 for the code of conduct too.

Are you fine with Google options for clang-format? I can work on that today and submit a tidy-up PR.

I'm happy to let you take a look at GitHub actions!

**Comment by amete** [comment]
I'm perfectly fine w/ the Google style, that's what we originally used in #23.

I'll look into Actions 😄
