### ISSUE TITLE
Decide on PRs for v2.0

### ISSUE THREAD

**Issue by graeme-a-stewart** [HSF/prmon#142]
Hi @amete 

I created a milestone for the next release. My target list for this is mainly #126 as this is a defect IMO. #141 is for discussion.

Can you add anything else we should do before we realease?

Thanks!

**Comment by amete** [comment]
Hi @graeme-a-stewart,

I completely agree. #141 is already in and #126 is imminent. On top of these, it would be nice to add #146 to the list. It's not super critical but should be easy enough. I'll get to it.

Best,
Serhan

**Comment by amete** [comment]
I think we closed all three issues: #126, #141, and #146. The remaining issues can be addressed as we go along. I believe we're ready for v2.0. What do you think @graeme-a-stewart?

**Comment by graeme-a-stewart** [comment]
Hi @amete - I agree, I think we can close this and start a new milestone for any remaining items (v2.1)
