### ISSUE TITLE
Add unit tests for the GPU metrics

### ISSUE THREAD

**Issue by amete** [HSF/prmon#147]
This can be optional but we should eventually add unit tests for the GPU metrics. Currently we have no coverage on that front. Now, this is a bit more involved I suppose because we possibly need to add a bit of `cuda` code and make our `cmake` setup smarter to be able to build it via `nvcc` etc. This is definitely not a showstopper but would be good to address sooner than later.

**Comment by graeme-a-stewart** [comment]
Yep, we should do this and at least check that we get some metrics back from GPUs, so it will require some extra codes in CMake to do this (fortunately, NVIDIA GPUs are well supported in CMake, but it may bump the minimum version).

**Comment by graeme-a-stewart** [comment]
We condsider closed by #195
