### ISSUE TITLE
Rename fails: No such file or directory

### ISSUE THREAD

**Issue by protopopescu** [HSF/prmon#15]
I see lots of these messages sometimes

```
rename fails: No such file or directory
prmon.json_tmp prmon.json_snapshot
```

Any idea why?

**Comment by protopopescu** [comment]
Perhaps file.close(); on line 158 instead of line 275, and using this file instead of tmpFile?

**Comment by amete** [comment]
There was a recent pull that was intended to fix the issue discussed at #11. Are you using the latest master?

**Comment by protopopescu** [comment]
Indeed, I've recompiled after this fix, and these messages were from a previous prmon instance. I'll watch to see if #13 fixes it. Thanks!

**Comment by graeme-a-stewart** [comment]
Hi @protopopescu - I just ran a long ATLAS job with the latest version and I didn't see this. So I am pretty sure it's fixed. (It came from leaking file handles and then running out of fds.)

**Comment by protopopescu** [comment]
Thank you, Graeme!
