### ISSUE TITLE
Add test against expected output fields

### ISSUE THREAD

**Issue by graeme-a-stewart** [HSF/prmon#152]
As revealed by #151 we don't check well enough for missing output fields, so we need to add a test for that

**Comment by spursbyte** [comment]
hello @graeme-a-stewart  can i work on this issue?

**Comment by graeme-a-stewart** [comment]
Hi @spursbyte - that would be really great. Would it be clear to you how to do this?

**Comment by spursbyte** [comment]
> Hi @spursbyte - that would be really great. Would it be clear to you how to do this?

yes i get the overall view about how to about the issue.but some more information about it from your side will be highly helpful. and should i start working on it or first make a proposal about it on how i will go about the issue??

**Comment by graeme-a-stewart** [comment]
Every monitor now defines a `paramater_list` object (https://github.com/HSF/prmon/blob/master/package/src/parameter.h) that contains the list of parameters and encodes if they will be only output for MAX values or of there is also a meaningful AVG value.

In principle this would then give the values to check against in the text and JSON output files.

I think this is probably better done as a C++ test so that the values to check can be "built in" from the class definitions.

Probably it's best that you think about it then and come up with a proposal that @amete and I can check.

Thanks a lot for your interest in the project!

**Comment by spursbyte** [comment]
> Every monitor now defines a `paramater_list` object (https://github.com/HSF/prmon/blob/master/package/src/parameter.h) that contains the list of parameters and encodes if they will be only output for MAX values or of there is also a meaningful AVG value.
> 
> In principle this would then give the values to check against in the text and JSON output files.
> 
> I think this is probably better done as a C++ test so that the values to check can be "built in" from the class definitions.
> 
> Probably it's best that you think about it then and come up with a proposal that @amete and I can check.
> 
> Thanks a lot for your interest in the project!

thank for the info and will get started with the proposal.
