### ISSUE TITLE
Tagging v2.1.0

### ISSUE THREAD

**Issue by amete** [HSF/prmon#169]
Hi @graeme-a-stewart,

Given that we have a number of fixes/updates/improvements, I guess we're ready for a new release 😄 , what do you think? Is there anything you'd like to get done beforehand?

Best,
Serhan

**Comment by graeme-a-stewart** [comment]
Hi @amete - yes, I think we're largely good to go on this one. There was one tiny defect I spotted, that's fixed in #171.

**Comment by graeme-a-stewart** [comment]
Oh, we should make sure that @chrisburr gets a mention in this release for #163

**Comment by amete** [comment]
Thanks @graeme-a-stewart. Just merged #171. I think we're good to go. Would you like to do the honors? I think the main differences w.r.t. the previous release are:

- Limiting decimal places in JSON output of averages (#161)
- Propagation of exit-codes (#163) [thanks to @chrisburr on this one]
- Updated `nvidia-smi` output parsing (#167)
- Python code improvements (#168)

Then we have the warning message for short processes (#166) and CMake bugfix for `clang-format` setting (#171).
 
Am I missing anything?

**Comment by graeme-a-stewart** [comment]
Yep, I'll get on to that. I think you cuaght all of the issues that were fixed this time around.

**Comment by graeme-a-stewart** [comment]
v2.1.0 is now tagged and relased

**Comment by amete** [comment]
> v2.1.0 is now tagged and relased

Thanks a lot @graeme-a-stewart!
