### ISSUE TITLE
Preparing v2.2.0

### ISSUE THREAD

**Issue by amete** [HSF/prmon#184]
I think we're ready for the next minor release, `v2.2.0`. The relevant changes since the last release are:

- Ability to disable components (#178 and #183)
- Patch for the network statistics rollover (#181)
- Bugfix for argument parsing (#179)
- Adding program version information to the JSON output (#176)
- Adding a python script that lossy compresses the text output (#172 thanks to @rmaganza 👍)

Anything I'm missing @graeme-a-stewart? 😄

**Comment by graeme-a-stewart** [comment]
Hi @amete - I don't think you missed anything. However, this will be release 2.2.0, right?

**Comment by amete** [comment]
That's absolutely right, I'm getting ahead of myself 😄

**Comment by graeme-a-stewart** [comment]
Will you do the honours this time?

**Comment by amete** [comment]
The new version should be up: https://github.com/HSF/prmon/releases/tag/v2.2.0

Please let me know if you spot any issues @graeme-a-stewart, many thanks.

Happy Friday! 🚀 😄

**Comment by graeme-a-stewart** [comment]
Happy Friday indeed! Thanks @amete 🥳
