### ISSUE TITLE
Count number of active CPUs for monitored processes

### ISSUE THREAD

**Issue by graeme-a-stewart** [HSF/prmon#186]
As requested by ATLAS, count the number of unique CPU cores that are used by a monitored job.

> [is it] possible to count the number of cores a given *process* runs on – we just saw a job that used a bit ‘too many’ cores (>40)

(from Paul Nilsson)

This information is available in

```
/proc/[PID]/task/[TID]/stat
```

The last active CPU identifier is the 39th field (from `man proc`).

We would loop over these and count unique CPU cores.

A few caveats:

- This will do a count for every *thread* that exists (so it will work for MT as well as MP)
- This tells you nothing about whether the thread is active or not, so this number could be higher that the number of cores with CPU intensive threads, when there are processes and threads that are only sporadically active

We'd like definite conformation that we understood the request properly and that it is genuinely useful before we discuss a concrete implementation. So please comment!

**Comment by amete** [comment]
Thanks a lot for starting the issue @graeme-a-stewart. Let me share my opinion here as well, for better documentation. 

We're already monitoring the total number of threads (`nthreads`) across all processes (`nprocs`). I think these should be enough to deduce how many cores the job can technically use. If we want to see how many cores the job has actually used on average in a given period of time, one could do `CPU-time/Wall-time` - which we already do in the ATLAS ADC monitoring plots, for example. 

Tracking the last CPU a thread ran on wouldn't really give too much useful information in my opinion. A single process w/ only the mother thread can actually run on every single CPU throughout its lifetime if the kernel decides it is best to switch it around for some reason (and it's not specifically pinned to one CPU). Also, as @graeme-a-stewart  noted above, it's impossible to deduce if a thread is active or not simply looking at the proc.

Maybe I'm missing some key point here.

**Comment by graeme-a-stewart** [comment]
OK, no further input received, so closing this request.
