### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by graeme-a-stewart** [HSF/prmon#187]
As there's been a lot of discussion in many communities about the implications of git's default `master` branch (which I don't want to repeat here), I'd like to propose that we rename the development branch of prmon to `main`.

Should be pretty easy to do, following instructions like this: <https://github.com/github/renaming>.

**Comment by amete** [comment]
Needless to say, I fully support this. Thanks for bringing it up @graeme-a-stewart.

**Comment by graeme-a-stewart** [comment]
OK, grand, let's do it then!

**Comment by graeme-a-stewart** [comment]
![Screen Shot 2021-02-24 at 10 17 53](https://user-images.githubusercontent.com/8511620/108978263-b8ebf280-7689-11eb-9c0d-6bc832d54d0e.png)
