### ISSUE TITLE
No data on walltime

### ISSUE THREAD

**Issue by graeme-a-stewart** [HSF/prmon#19]
I realised our summary file doesn't have a walltime measure - it should.

I don't know if we can get this from /proc, or if we just guesstimate that the wall time is the wall clock time of `prmon` itself.

**Comment by amete** [comment]
I see `/proc/[pid]/stat` has `starttime` which is defined to be: `The time the process started after system boot`. For the mother pid we can simple do: `currentTime - uptime + starttime`, where we get the `uptime` from `/proc/uptime` and `currentTime` from within `prmon`, to get the time the mother process started and use that to calculate the elapsed time. This might be more robust if the `prmon` is started w/ a delay. I'll take a look at this.

BTW, I noticed that when we calculate IO average values, we use the `startTime` as approximately the time `prmon` started. We can also update that.

**Comment by amete** [comment]
I have a first implementation of this at: https://github.com/HSF/prmon/tree/master-add-walltime

I'll open a PR where we can discuss the details.

**Comment by amete** [comment]
This is fixed in #20, closing.
