### ISSUE TITLE
Submodule missing from source tarball

### ISSUE THREAD

**Issue by nikoladze** [HSF/prmon#209]
The spdlog submodule is missing from the source tarball (https://github.com/HSF/prmon/archive/refs/tags/v3.0.0.tar.gz). Noticed this since i use the source tarball for an [AUR package of prmon](https://aur.archlinux.org/packages/prmon/). There are workarounds (i could directly clone the git or manually fetch the submodule or use the binary package), but maybe there is a way to include the submodule in the source tarball.

**Comment by graeme-a-stewart** [comment]
Hello @nikoladze - apologies for the very late reply on this. I somehow missed that you raised this ticket. Let's see what we can do, the tarball is prepared by `cmake` so it should be possible to ensure that it includes spdlog as well.

**Comment by graeme-a-stewart** [comment]
Actually the source tarball is prepared by github itself (cmake only does the static build binary tarball). We need to investigate workarounds.
