### ISSUE TITLE
C++ code formatting

### ISSUE THREAD

**Issue by amete** [HSF/prmon#21]
I believe we can make things look better/more consistent by adopting a standard format. 

I created a new branch: https://github.com/HSF/prmon/tree/master-formatting where I passed the C++ code through clang-format w/ Google style. 

I can put in a PR if others also agree. I'll be happy to hear any comments, @graeme-a-stewart :) ?

**Comment by graeme-a-stewart** [comment]
I had a look and the code now looks a lot better in Eclipse for me, so I would be happy to take this as a PR.

BTW, how did you setup/get clang-format? I don't find it in brew and it doesn't seem to be part of the Xcode suite on my Mac.

**Comment by amete** [comment]
Thanks @graeme-a-stewart. I opened #23 (note that this is a different branch than what I had above). 

I actually have clang-format installed on my mac via Homebrew : `brew install clang-format`. That was the easiest tbh :)

**Comment by graeme-a-stewart** [comment]
Oh yeah, why did I not see that - yes, it just worked 👍
