### ISSUE TITLE
Review gtest version

### ISSUE THREAD

**Issue by graeme-a-stewart** [HSF/prmon#231]
We use rather an old version of gtest at the moment (https://github.com/HSF/prmon/blob/881305c9e1f90f10eed35aa7042b2b842ec8c594/package/tests/CMakeLists.txt#L22C9-L22C45) - not even sure what version this is.

We should probably bump this to the latest release (maybe even just make it a submodule, for easier maintenance?).

**Comment by testgithubsonika** [comment]
I am willing to do this ,please assign me this issue.
