### ISSUE TITLE
prmon doesn't seem to handle SIGUSR1 correctly in the ATLAS grid jobs

### ISSUE THREAD

**Issue by amete** [HSF/prmon#235]
This one is from Paul Nilsson. Let me copy paste his email below:

> Can you please check the signal handling in prmon and verify that it correctly handles the SIGUSR1 kill signal? It looks like prmon becomes a zombie after being killed almost all the time. I’m killing it like [1].
 
> I get a None most of the time (os.WIFEXITED(status) returns False).

[1]

```
try:
    # Send SIGUSR1 signal to the process group
    os.killpg(pid, sig)

    # Wait for the process to finish
    _, status = os.waitpid(pid, 0)

    # Check the exit status of the process
    if os.WIFEXITED(status):
        return os.WEXITSTATUS(status)
    else:
        # Handle abnormal termination if needed
        return None
except OSError as exc:
    # Handle errors, such as process not found
    logger.warning(f"exception caught: {exc}")
    return None
```

**Comment by graeme-a-stewart** [comment]
Hi, I had a look and AFAICT prmon is handling SIGUSR1 just fine.

@PalNilsson, just having a look at your code you call `killpg` with `pid`; then you wait for `pid` *indicating to me that this is the `pid` of prmon*. However, are you certain that `pid` is the *process group ID* that corresponds to prmon? After all, you launch prmon as a child, so the `pgid` for prmon is more likely to be the pilot's `pid`.

I give you an example:

First, write a very simple wrapper around prmon:

```sh
#! /bin/sh
./package/prmon -- sleep 600
echo All done with $?
```

Now I run this wrapper, `./parent.sh`. And look at the `pid` and `pgid`s:

```sh
➜  prmon git:(main) ps -eo cmd,pid,ppid,pgid    
CMD                             PID    PPID    PGID
[...]
/bin/sh ./parent.sh          647435  646060  647435
./package/prmon -- sleep 60  647436  647435  647435
sleep 600                    647437  647436  647435
```

As you can see for prmon `pgid != pid`!

Maybe I am missing something, depending on how you're spawning things, but I think this is worth checking.

P.S. For the record if I now do a `kill -s USR1 647436` (N.B. prmon's pid!), I get:

```sh
➜  prmon ./parent.sh                 
All done with 0
```

Which is just what should happen (`SIGUSR1` is considered a normal exit for prmon).

**Comment by graeme-a-stewart** [comment]
After discussing this with Paul, we concluded that the issue was caused by the pilot sending the signal to the wrong process.
