### ISSUE TITLE
PrMon in conda-forge?

### ISSUE THREAD

**Issue by sciaba** [HSF/prmon#237]
Would it make sense to be able to install PrMon using conda? Personally I would find it rather convenient.

**Comment by sciaba** [comment]
I just found out this is already the case!

**Comment by graeme-a-stewart** [comment]
I think @chrisburr did this a long time ago - I guess it still works...?

**Comment by sciaba** [comment]
Indeed it does, as I discovered shortly after creating this issue. Sorry for the noise!
