### ISSUE TITLE
Better option parsing

### ISSUE THREAD

**Issue by graeme-a-stewart** [HSF/prmon#3]
The option parsing in `prmon` is a bit rubbish and not easy to extend.

Moving to `Boost.Program_options` would seem to be the natural way to go (pretty easy to satisfy this dependency).

**Comment by graeme-a-stewart** [comment]
Proposed fix in #7

**Comment by graeme-a-stewart** [comment]
OK, after some consideration of how fragile Boost can be, it seemed more prudent to just use a simple parser, like `getopt`. See #10 for PR.

**Comment by amete** [comment]
Fixed in #10.
