### ISSUE TITLE
Review use of RapidJSON

### ISSUE THREAD

**Issue by graeme-a-stewart** [HSF/prmon#38]
As noted in #37, I find the current use of RapidJSON to be rather unsatisfying. Creating a `c_str` and then using the DOM model is fragile (and it core dumps if you get it wrong).

It would (probably) be rather better to use the SAX model and have a `Writer` assemble the JSON object structure that we need.

Anyway, at least other ways to do this should be thought about...

**Comment by amete** [comment]
Since we no longer use RapidJSON this issue became obsolete. Therefore, I'm closing it.
