### ISSUE TITLE
Anomolous SIGCHLDs

### ISSUE THREAD

**Issue by graeme-a-stewart** [HSF/prmon#41]
This is more an observation than a problem. When debugging the handling of child processes in `prmon` I find that every time we wait for the condition variable, a `SIGCHLD` is issued. It must be related to an internal thread being spawned to handle this.

It's probably not really a problem, but it might be worth reviewing the way that we do the waiting and handling of the `SIGUSR1` condition.

**Comment by graeme-a-stewart** [comment]
Fixed in #63 where the rather unnecessary handling of SIGUSR1 using condition variables was addressed.

**Comment by amete** [comment]
#63 merged, closing this.
