### ISSUE TITLE
Combined plots

### ISSUE THREAD

**Issue by sciaba** [HSF/prmon#45]
Would it be possible to change prmon_lot.py in such a way that one can give a list as argument to --yvar, which would produce a stack of plots in a single png file? This would avoid having to manually combine pngs and it would naturally show the time correlation among different metrics.
Thanks,
Andrea

**Comment by sciaba** [comment]
In addition it would be useful to add an option to specify if the plots should be stacked or superimposed. The latter makes more sense when combining metrics expressed in the same unit (for example VMEM vs RSS, or rchar vs wchar).

**Comment by amete** [comment]
Hi Andrea,

Thanks a lot for the super useful feedback. I just pushed `master-plotting-updates` which should have these implemented. You can now pass a comma separated list to `--yvar`:

```
./prmon_plot.py [...] --yvar vmem,pss,rss
```

This should produced plots similar to:

![prmon_time_vs_vmem_pss_rss_memmon](https://user-images.githubusercontent.com/7428938/40546508-c23adc34-602f-11e8-91f1-836932998335.png)

You can also specify `--stacked` which will stack the distributions (superimposed by default):

```
./prmon_plot.py [...] --yvar vmem,pss,rss --stacked
```

Could you give it a spin and let me know? Then I can open an PR. Many thanks.

Best,
Serhan

**Comment by sciaba** [comment]
I'll try the command ASAP but the output you attached is beautiful!
Thanks,
Andrea

**Comment by sciaba** [comment]
I tried it and it worked as expected.
Cheers,
Andrea

**Comment by amete** [comment]
Thanks Andrea! I opened PR #53.

-s
