### ISSUE TITLE
Axis labels broken

### ISSUE THREAD

**Issue by sciaba** [HSF/prmon#46]
In prmon_plot.py, the axis labels are set to [kb] when the field is PSS, VMEM, RSS or SWAP, but in prmon.txt the names are lowercase, so the axis labels do not get printed when e.g. --xvar pss.

**Comment by amete** [comment]
Hi Andrea,

During the code restructuring we changed the header a little bit, which caused this. Hopefully this also is resolved in the `master-plotting-updates`.  I'd appreciated if you can give it a go and let me know.

Best,
Serhan

**Comment by sciaba** [comment]
Works fine now.
Cheers,
Andres

**Comment by amete** [comment]
Thanks Andrea!

-s

**Comment by amete** [comment]
Fixed in #53, closing.
