### ISSUE TITLE
prmon VMEM and PSS sizes seem to be wrong

### ISSUE THREAD

**Issue by graeme-a-stewart** [HSF/prmon#47]
Testing by @sciaba showed that there's a problem with VMEM and PSS. Evidently there's a bug in the re-implementation of the smaps parser in `memmon.cpp`.

Changes to `memmon` should be validated against the built-in `MemoryMonitor` run by ATLAS jobs.

**Comment by sciaba** [comment]
If you like you can find the outputs on pmpe02.cern.ch, under
/data/sciaba/atlas/atlas-sim-180517
(I hope you can login to the machine with your CERN account).

**Comment by graeme-a-stewart** [comment]
Yeah, I found the bug now - I wasn't flushing to the end of the line in the smaps file.

Fixed, but I will write a few tests to check it dosn't break again (which I should have done in the original PR, ahem!).

**Comment by sciaba** [comment]
Great! I'll re-run my test as soon as the fix is committed.

**Comment by graeme-a-stewart** [comment]
Hi @sciaba - the fix is in #48 and you can pre-test it by compiling the `smaps-parse-fix`. It was a really simple issue in the end, where after reading key:value pairs from the smaps file, the reminder of the line was not ignored.

I have tested it using a new test case, but it does need to be validated properly against a real workload. The ATLAS one is good as we have the old MemoryMonitor data to compare against.

**Comment by sciaba** [comment]
Sorry, my fault. prmon uses kB (which I converted to GB using 1 GB = 1e6 kB, and the MM plotting script uses GB where 1 GB = 1024 * 1024 kB, so eveything checks out!

**Comment by graeme-a-stewart** [comment]
That's great! My test job is still running (I think I have too many events), so I am very happy you also checked.

@amete - then #48 should be merged when you can.

**Comment by amete** [comment]
Hey guys,

I just merged #48 that fixes this.

-s

**Comment by amete** [comment]
Hey guys,

Before re-opening this I wanted to run this by you to make sure I'm not messing something obvious here. I ran a simple q431 job over 100 events on a single core and listened to it with both `MemoryMonitor` and `prmon`:

```
eco_tf.py --AMI q431 --maxEvents 100 --steering doRAWtoALL > q431.log &
mypid=$!
prmon --pid $mypid --filename prmon.txt --json-summary prmon.json --interval 30 &
MemoryMonitor --pid $mypid --filename memmon.txt --json-summary memmon.json --interval 30 &
```

I get quite different results. This is what `prmon` reports:

![prmon_time_vs_vmem_pss_rss_prmon](https://user-images.githubusercontent.com/7428938/40548037-da4ae7a2-6033-11e8-9d70-8465bcf4d198.png)

and this is what `MemoryMonitor` reports:

![prmon_time_vs_vmem_pss_rss_memmon](https://user-images.githubusercontent.com/7428938/40548065-ed0838a4-6033-11e8-9f98-8cf0cddcf468.png)

Looking at the outputs, `prmon` gives:

```
Time  wtime stime utime pss rss swap  vmem  rchar read_bytes  wchar write_bytes rx_bytes  rx_packets  tx_bytes  tx_packets
1527254263  0 0 0 5048  5756  0 28896 728267  3260416 0 0 628 9 110 1
1527254294  32  1 0 20006 22248 0 192104  4283729 18927616  149818  53248 366766  917 70859 400 
1527254325  62  1 0 19975 22224 0 192104  4404987 18927616  432700  348160  830294  1706  102905  648 
1527254356  93  1 0 19975 22224 0 192104  4453565 18927616  544451  466944  9440637 8358  300251  1862
1527254387  124 1 1 20219 22468 0 192408  4796281 18927616  1246846 1191936 10213692  9851  545449  2823
1527254418  155 1 1 20210 22412 0 192408  4823199 18927616  1307383 1286144 10761250  10889 695502  3395
1527254449  186 1 1 20210 22412 0 192408  4935631 18927616  1558657 1552384 13255032  15056 1488271 6549
1527254480  217 1 1 20210 22412 0 192408  5315757 18927616  2404413 2408448 15734055  17469 1676698 7540
1527254511  248 1 1 20210 22412 0 192408  5445808 18927616  2694811 2711552 16355678  18853 1961333 8351
1527254542  279 1 1 20210 22412 0 192408  5468532 18927616  2745254 2777088 80623827  64166 3419219 22926
1527254573  311 1 1 20210 22412 0 192408  5496842 18927616  2808165 2846720 100538639 79363 4158609 27753
1527254604  341 1 1 20210 22412 0 192408  5506741 18927616  2830096 2879488 111344282 87970 4671603 30883
1527254635  372 1 1 20210 22412 0 192408  5552547 18927616  2931798 2985984 118271423 94561 5323463 34075
1527254666  403 1 1 20210 22412 0 192408  5742008 18927616  3350652 3416064 118402434 94972 5334797 34171
1527254697  434 1 1 20210 22412 0 192408  5798849 18927616  3479810 3547136 118429326 95282 5337267 34201
1527254728  465 1 1 20210 22412 0 192408  5808616 18927616  3501480 3575808 118453187 95603 5338507 34216
....
```

while `MemoryMonitor` gives:

```
Time  VMEM  PSS RSS Swap  rchar wchar rbytes  wbytes
1527254263  32968 5100  5804  0 748388  0 3461120 0
1527254294  928780  376823  383196  0 21441354  1106589 272224256 77824
1527254325  1343416 692926  699456  0 29791174  1509467 335470592 376832
1527254356  1605276 923797  930380  0 37728977  1754282 393101312 503808
1527254387  1667404 977222  983840  0 40238337  3005471 408092672 1236992
1527254418  1231832 572061  578212  0 61954606  6389952 848130048 3805184
1527254449  1316340 642036  648368  0 63325753  6765118 881618944 4087808
1527254480  2203424 1084710 1091060 0 108127993 8601411 1558401024  5562368
1527254512  2418252 1286932 1293284 0 151380465 9481284 1741553664  6352896
1527254543  2610452 1482484 1488836 0 154184160 9560154 1741561856  6426624
1527254574  3108628 1752084 1758436 0 156988413 9654936 1741561856  6512640
1527254605  3360532 2119548 2125900 0 159776287 9695010 1741561856  6553600
1527254636  3539712 2257632 2263984 0 290898021 9887222 1897476096  6725632
1527254667  5180000 3807996 3814348 0 324617465 12502375  2062548992  9183232
1527254699  5805508 4349508 4355860 0 335365429 13797205  2213842944  10448896
1527254730  5893464 4328766 4335120 0 349124559 19713345  2235699200  16416768
1527254761  5923008 4434890 4441244 0 357761586 37544893  2249723904  34299904
1527254792  6030624 4451226 4457580 0 369756546 56787297  2256175104  53612544
1527254823  6030632 4430034 4436388 0 378227012 81210181  2261155840  78094336
....
```

It's like what `prmon` sees is an idle process for a long time whereas `MemoryMonitor` seems to make more sense. 

All these are on an SLC6 machine w/ the latest 21.0 Athena nightly (`prmon` is the latest master). Did you guys test the latest master of `prmon` w/ reconstruction?

Best,
Serhan

**Comment by graeme-a-stewart** [comment]
Hi @amete - I can't see anything wrong in what you did, so let's reopen and I will investigate.

**Comment by amete** [comment]
Thanks @graeme-a-stewart, I'll also make a clean test from scratch just to confirm.

**Comment by graeme-a-stewart** [comment]
OK, interesting - the `childMem` unit test fails on SLC6.

Investigating, I see the file containing the child PIDs does not exist in SLC6 (`/proc/PID/task/PID/children`).

I need to work out a way to do the new style PID parsing in this old kernel or revert back to the old style `pstree` parsing.
