### ISSUE TITLE
RFC: Change default sampling time

### ISSUE THREAD

**Issue by graeme-a-stewart** [HSF/prmon#49]
The current sampling time in prmon is very short, just 1 second:

https://github.com/HSF/prmon/blob/a273db9b97e4269a1093a37b361ce100c2eaf071/package/src/prmon.cpp#L255

This is great for doing short tests, but it seems rather too short for measuring grid workflows that last O(hours). The old MemoryMonitor default was rather too long though, at 600 seconds (https://gitlab.cern.ch/atlas/athena/blob/master/Control/AthenaMP/src/memory-monitor/MemoryMonitor.cxx#L244). In practice, we used 30 seconds in the production transforms (https://gitlab.cern.ch/atlas/athena/blob/master/Tools/PyJobTransforms/python/trfExe.py#L664).

My gut feeling is that somewhere between 10 seconds and 60 seconds is probably right. It can always be changed with the `interval` argument, but a better default seems sensible to me.

@amete , @sciaba , johannes.elmsheuser@cern.ch what do you think?

**Comment by sciaba** [comment]
Hi Graeme,
size of the prmon.txt is not an issue of course, the impact on performance of 1-second sampling should be negligible (it just parses files in /proc which are in memory by definition), so there shouldn't be any problem with 1-second intervals, but I agree that it's overkill and 10-second intervals are more sensible.

**Comment by elmsheus** [comment]
Hi all,
In the Panda pilot the monitoring interval of the MemoryMonitor is set to 60 seconds using the "--interval" parameter:
 MemoryMonitor --pid 32433 --filename memory_monitor_output.txt --json-summary memory_monitor_summary.json --interval 60

For memory and disk I/O growth/absolute size measurements a 60seconds interval is absolutely fine and produces reasonable sized text files with more than enough infos when used in hour long production jobs - for I/O (disk/network) rates measurements the interval might be a bit too large, but we have to compromise when this is used in production.

So using a default of 10,30 or 60s sounds reasonable and it will be anyway adjusted when used in a production environment.
Cheers, Johannes

**Comment by sciaba** [comment]
Just to amend my previous comment on prmon having a negligible impact, as this does not seem to be the case as Graeme discovered. Clearly the default should be chosen so to have a reasonably small impact in typical conditions (e.g. less than 1% CPU time going to prmon?).

**Comment by amete** [comment]
Just a comment on the default sampling. I think any value is equally OK. Ideally the sampling interval depends on how long the process is going to run (i.e. shorter jobs are sampled more frequently and longer jobs less frequently). Unfortunately, it's impossible to know this a priori from the monitoring side.

In any case, if we're going to deviate from the current 1 sec (which in practice fluctuates by 1 sec or so after all the refactoring based on a few quick tests), we should update the unit tests (which can run as short as a few secs only and I believe we rely on the default sampling interval).

**Comment by amete** [comment]
Implemented in #57, closing.
