### ISSUE TITLE
prmon consuming too much CPU resource

### ISSUE THREAD

**Issue by graeme-a-stewart** [HSF/prmon#50]
Running `prmon` on an ATLAS 8 core simulation job I notice that after about an hour's runtime:

```sh
aiatlas161:/build/graemes/montest/sim$ ps gux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
graemes  24285 26.0  0.0  15212  1372 pts/2    S+   12:12  17:10 ../bin/prmon --interval 10 -- Sim_tf.py --inputEVNTFile=EVNT.13043099._000859.pool.root.1 --maxEvents=1000 --postIncl
graemes  24286  0.0  0.3 633780 97532 pts/2    S+   12:12   0:02 python /cvmfs/atlas.cern.ch/repo/sw/software/21.0/AtlasOffline/21.0.15/InstallArea/x86_64-slc6-gcc49-opt/share/Sim_tf
graemes  24325  0.0  0.0   9704  1428 pts/2    S+   12:12   0:00 /bin/sh ./runwrapper.EVNTtoHITS.sh
graemes  24326  1.1  0.0  17012  1132 pts/2    S+   12:12   0:45 MemoryMonitor --pid 24325 --filename mem.full.EVNTtoHITS --json-summary mem.summary.EVNTtoHITS.json --interval 30
graemes  24327  2.5  6.3 2683568 1890308 pts/2 Sl+  12:12   1:39 /cvmfs/atlas.cern.ch/repo/sw/software/21.0/sw/lcg/releases/LCG_87/Python/2.7.10/x86_64-slc6-gcc49-opt/bin/python -tt 
graemes  25206 99.9  6.3 2686716 1901632 pts/2 R    12:16  61:21 /cvmfs/atlas.cern.ch/repo/sw/software/21.0/sw/lcg/releases/LCG_87/Python/2.7.10/x86_64-slc6-gcc49-opt/bin/python -tt 
graemes  25207 99.9  6.3 2691088 1904744 pts/2 R    12:16  61:19 /cvmfs/atlas.cern.ch/repo/sw/software/21.0/sw/lcg/releases/LCG_87/Python/2.7.10/x86_64-slc6-gcc49-opt/bin/python -tt 
graemes  25208 99.9  6.3 2689316 1904996 pts/2 R    12:16  61:20 /cvmfs/atlas.cern.ch/repo/sw/software/21.0/sw/lcg/releases/LCG_87/Python/2.7.10/x86_64-slc6-gcc49-opt/bin/python -tt 
graemes  25209 99.9  6.3 2687544 1906452 pts/2 R    12:16  61:20 /cvmfs/atlas.cern.ch/repo/sw/software/21.0/sw/lcg/releases/LCG_87/Python/2.7.10/x86_64-slc6-gcc49-opt/bin/python -tt 
graemes  25210 99.9  6.3 2691420 1903956 pts/2 R    12:16  61:21 /cvmfs/atlas.cern.ch/repo/sw/software/21.0/sw/lcg/releases/LCG_87/Python/2.7.10/x86_64-slc6-gcc49-opt/bin/python -tt 
graemes  25211 99.9  6.3 2688096 1902832 pts/2 R    12:16  61:20 /cvmfs/atlas.cern.ch/repo/sw/software/21.0/sw/lcg/releases/LCG_87/Python/2.7.10/x86_64-slc6-gcc49-opt/bin/python -tt 
graemes  25215 99.9  6.3 2688372 1903712 pts/2 R    12:16  61:21 /cvmfs/atlas.cern.ch/repo/sw/software/21.0/sw/lcg/releases/LCG_87/Python/2.7.10/x86_64-slc6-gcc49-opt/bin/python -tt 
graemes  25216 99.9  6.3 2688648 1907700 pts/2 R    12:16  61:20 /cvmfs/atlas.cern.ch/repo/sw/software/21.0/sw/lcg/releases/LCG_87/Python/2.7.10/x86_64-slc6-gcc49-opt/bin/python -tt 
```

Which indicates that `prmon` is sucking up about 1/4 of a CPU, 17 minutes. Compare that with MemoryMonitor that's used only 45 seconds. 

prmon's cadence is 10 seconds, cf. MemoryMonitor at 30s. But even accounting for that this is about a x7 degradation. This is way too high a resource cost for a monitoring program. We have to profile`prmon` and see what's costing so much.

**Comment by graeme-a-stewart** [comment]
Just another piece of info from this run, the smaps files for the athena workers are pretty chunky:

```
aiatlas161:/build/graemes/montest/sim$ cat /proc/25206/smaps | wc 
  20816   72690  770964
```

cf. the one for prmon itself:

```
aiatlas161:/build/graemes/montest/sim$ cat /proc/24285/smaps | wc 
    576    1989   18910
```

**Comment by amete** [comment]
Hi @graeme-a-stewart,

Yes, 25% sounds quite a lot. I'm gonna take a look at this, assigning to myself. I wonder if we can monitor `prmon` w/ another instance of `prmon` :)

-s

**Comment by sciaba** [comment]
Graeme, are you sure that the -i 10 option is properly taken into account? I am running prmon with --interval 30 and prmon.txt looks like

1527006295      186     47      379     10864260        31135856        0       52681148        387448334       2064166912      40686956        37515264        325501594       297599  34544464        159977
1527006297      189     47      379     10875992        31147584        0       52700604        387466661       2064166912      40693069        37523456        332170913       304205  35409613        163847
1527006299      191     47      380     10920951        31192300        0       52747708        387582881       2064166912      40712708        37527552        346476326       316269  36490448        169747
1527006301      193     47      382     10943583        31214204        0       52784572        388105871       2064166912      40779920        37732352        361232401       329429  38009966        176781

so wtime indicates that prmon.txt gets a new line even more often than once per second.

**Comment by sciaba** [comment]
(sorry, the snippet I sent is not the best, look for example
1527006108      1       0       0       5774    6588    0       40676   920976  4091904 0       0       536     7       584     4
1527006109      1       0       0       11319   13260   0       99984   1802686 6610944 178     4096    716     10      1060    6
1527006110      3       0       0       17721   19768   0       127216  3386164 10665984        53663   4096    896     13      1702    9
1527006111      3       0       0       36071   38376   0       230724  4366335 46960640        576056  4096    1556    24      7686    27
1527006112      5       0       0       86207   88528   0       364120  4374176 119316480       576056  4096    1676    26      7884    28
1527006113      6       1       1       127639  129972  0       411896  5550452 140939264       748963  4096    1856    29      8328    30
)
I have the impression that there is no waiting time whatsoever.

**Comment by amete** [comment]
I think `lastIteration` is not correctly set at each iteration in `prmon.cpp`. I'll create a ticket.

-s

**Comment by graeme-a-stewart** [comment]
(If this is explained by #51, In any case, we should profile the code!)

**Comment by graeme-a-stewart** [comment]
Just an update, running an 8 process AthenaMP job, I see the following some way through the job:

```
16869 graemes   20   0 4621584   3.1g 180888 R 100.0 11.0   6:19.97 athena.py                                                                                                                  
16870 graemes   20   0 4689368   3.0g 187288 R 100.0 10.7   6:19.99 athena.py                                                                                                                  
16864 graemes   20   0 4640876   3.0g 182376 R 100.0 10.7   6:19.98 athena.py                                                                                                                  
16866 graemes   20   0 4558056   3.0g 179840 R 100.0 10.6   6:19.83 athena.py                                                                                                                  
16863 graemes   20   0 4585440   3.0g 178840 R 100.0 10.6   6:20.13 athena.py                                                                                                                  
16865 graemes   20   0 4559496   3.0g 179084 R 100.0 10.6   6:19.86 athena.py                                                                                                                  
16867 graemes   20   0 4583180   3.0g 183864 R 100.0 10.5   6:20.10 athena.py                                                                                                                  
16868 graemes   20   0 4565584   3.0g 180452 R 100.0 10.4   6:20.15 athena.py                                                                                                                  
15970 graemes   20   0 3359524   2.2g 139784 S   0.3  7.7   2:42.50 athena.py                                                                                                                                                                                                                      
15959 graemes   20   0   15752   1220    880 S   0.0  0.0   0:10.16 prmon                                                                                                                      
15969 graemes   20   0   17560   1156    880 S   0.0  0.0   0:10.78 MemoryMonitor
```

So `prmon` and `MemoryMonitor` use basically the same resources (10s). This compares well to the resources used by the application (3200s), being about 0.3%.

This is for a 30s sampling interval.

**Comment by amete** [comment]
I also ran an 8 process AthenaMP job which I monitored w/ `prmon` that is also monitored w/ another instance of `prmon`. Here is the CPU and memory consumption of the `prmon` that listened to the AthenaMP job:

![prmon_wtime_vs_utime_stime](https://user-images.githubusercontent.com/7428938/40712058-01f2f264-63fd-11e8-91eb-3761bc696aef.png)

![prmon_wtime_vs_vmem_pss_rss](https://user-images.githubusercontent.com/7428938/40712059-020d508c-63fd-11e8-9abb-5fb2e4bc9ca3.png)

The AthenaMP job took approximately 1830 seconds wall-time [ 205 (system) + 2950 (user) =  3155 seconds of CPU-time ], while the `prmon` listening to it used 15 (system) + 3 (user) = 18 seconds of CPU-time, which is about 0.5%. This looks consistent w/ @graeme-a-stewart's results. 

We also used about 0.5 MB of PSS and about 1 MB of RSS, which is fairly acceptable I think.

If there are no objections I'm going to close this ticket as the sampling interval fix seems to resolve it. 

Please let me know, many thanks :)

**Comment by graeme-a-stewart** [comment]
Yes, I agree - this we can close, though I still think we should have a profile build option to see where we do consume resources.

The plots are great though as they show

- Most of the CPU goes to the system, i.e., actually reading the files from /proc
- The consumption gradient shows the expected variation on the number of processes

All of which I find reassuring.
