### ISSUE TITLE
lastIteration is not correctly updated causing continuous sampling

### ISSUE THREAD

**Issue by amete** [HSF/prmon#51]
I think we need to update `lastIteration` in the loop properly in `prmon.cpp`. Right now, we only do this once at the beginning and then never, causing [this line](https://github.com/HSF/prmon/blob/master/package/src/prmon.cpp#L175) to be true hence we end up sampling continuously. 

Can perhaps fix #50.

**Comment by graeme-a-stewart** [comment]
Hi - yes, it looks like that's the problem. In my big simulation job I have been running for 31076s and there are 21278 samples.

This is x20 more than the sample rate of MemoryMonitor reported in #50 so it would explain the x20 higher CPU consumption.
