### ISSUE TITLE
Support a profile build option

### ISSUE THREAD

**Issue by graeme-a-stewart** [HSF/prmon#58]
`prmon` resource consumption seems to be very reasonable, even for 8 core multi-process jobs (0.5% as seen in #50), however we should support a profiling build option so that we can analyse where we do actually consume resources.

**Comment by amete** [comment]
I did a few additional tests w/ VTune just for fun. This is on SLC6, running the CPU burner for 120 seconds w/ 2 processes and 2 threads. 

What I deduce is that 92% of the resource consumption is essentially from `pstree` (mainly opening directories, reading etc.):

![screen shot 2018-05-30 at 2 48 19 pm](https://user-images.githubusercontent.com/7428938/40720952-861e0900-6418-11e8-8778-c89effb22fd7.png)

Only 8% is running actual `prmon` stuff. When we're in `MemoryMonitor` we seem to spend about 30% in `netmon::read_raw_network_stats` and about 25% in `memmon::update_stats` (I don't think there is anything special w/ these - could have been other `Xmon` as the implementations are all the same). I guess (looking at the caller/callee) these are the parts where we extract stuff via `>>` etc. 

![screen shot 2018-05-30 at 2 50 14 pm](https://user-images.githubusercontent.com/7428938/40721881-17c71d18-641b-11e8-8f2d-ad8daa86e29f.png)

In any case, this was done mostly for fun (and playing around w/ VTune). I fully support having a profiling build option, needless to say :)
