### ISSUE TITLE
Create the first tag of prmon

### ISSUE THREAD

**Issue by amete** [HSF/prmon#59]
I think we're at (or close to) a point where the `prmon` is stable enough that we can create the first tag, which we can use as basis to perhaps replace `MemoryMonitor` with `prmon` in the ATLAS workflow. There are a few open issues currently but I don't think these are showstoppers. What do you guys think, @graeme-a-stewart, johannes.elmsheuser@cern.ch?

**Comment by graeme-a-stewart** [comment]
Yeah, I think we're at the point that we should tag this.

I would think we should talk to the LIM about adding `prmon` into the LCG release, which would mean that ATLAS doesn't have to build it as an external. As a common utility tool it should really live there (and that also means we solve the JSON build dependency only once).

**Comment by graeme-a-stewart** [comment]
On that last point, I checked and current LCG releases have `simplejson`:

http://lcginfo.cern.ch/pkg/simplejson/

**Comment by graeme-a-stewart** [comment]
Oh, I am an idiot - we use RapidJSON, not SimpleJSON...

**Comment by amete** [comment]
Ehehe, it happens to the best of us :)

RapidJSON is a header-only library. So including it in an LGC release should be super simple - I hope. Adding `prmon` to LCG is also a great idea. I wonder if this can also eliminate possible problems that we're having w/ linking `MemoryMonitor` against the correct `Threads` library. We hopefully won't have to run two different version of the tool (one w/ the TRF and one w/ the pilot) :)

**Comment by graeme-a-stewart** [comment]
OK, I think when #63 is merged we can make the first tag.

**Comment by graeme-a-stewart** [comment]
I think we're in good shape to do this now, so I would propose we create a simple tag, like `1.0`.

I think it would also be a good idea to make a branch as well, so that we can separate fixes and minor improvements from any significant work. Although this could generate more work for us, not structuring things properly from the start is more likely to lead to a mess.

Branch name should be `v1` to disambiguate from any tag names.

**Comment by graeme-a-stewart** [comment]
Actually, let's not over complicate things - let's have a `stable` branch. We don't need to support multiple stable releases, just one is fine.

**Comment by amete** [comment]
I can create a branch `stable` and tag the first version from it as `v1.0`, would that work? I agree that we probably won't need/have multiple stable releases at a time.

**Comment by graeme-a-stewart** [comment]
Yes for the `stable` branch - thanks.

For the tag I'd vote for for `v1.0.0`, just to consistently have the patch level in there as well.

**Comment by amete** [comment]
We now have a branch `stable` and our first tag `v1.0.0`! Congrats @graeme-a-stewart :)

**Comment by graeme-a-stewart** [comment]
Yay! 👍
