### ISSUE TITLE
Tweaks to axis labels and plot titles needed

### ISSUE THREAD

**Issue by sciaba** [HSF/prmon#65]
For prmon plots to be good for publications and presentations, some minor issues with overlapping text labels should be fixed. See as an example:

![prmon](https://user-images.githubusercontent.com/12764525/41041101-7a551fb0-699e-11e8-84f2-4918a0ddd2de.png)

**Comment by amete** [comment]
I just pushed a new branch named `master-improve-plotting-script` where I tried to address this issue. I tried to beautify the axis/legend labels, properly assign the units etc. This also addresses the plotting issues mentioned in #64.

Some examples are:

`./prmon_plot.py --xvar wtime --yvar vmem,pss,rss --stacked`
![prmon_wtime_vs_vmem_pss_rss](https://user-images.githubusercontent.com/7428938/41043737-de3731ac-69a4-11e8-88bb-a729746e7903.png)

`./prmon_plot.py --xvar wtime --yvar utime,stime,wtime`
![prmon_wtime_vs_utime_stime_wtime](https://user-images.githubusercontent.com/7428938/41043745-e4d33f7e-69a4-11e8-8c62-794501e2bd57.png)

`./prmon_plot.py --xvar wtime --yvar utime,stime --diff`
![prmon_wtime_vs_diff_utime_stime](https://user-images.githubusercontent.com/7428938/41043755-eb287e84-69a4-11e8-9f88-52d7a6248f11.png)

`./prmon_plot.py --xvar wtime --yvar rx_bytes,tx_bytes --diff`
![prmon_wtime_vs_diff_rx_bytes_tx_bytes](https://user-images.githubusercontent.com/7428938/41043764-f02a9570-69a4-11e8-96eb-6569c8336e28.png)

Could you give it a shot and let me know? Let me tag @graeme-a-stewart in case he also wants to comment.

Many thanks.

-s

**Comment by graeme-a-stewart** [comment]
@amete - thanks! My suggestion is that one can somehow scale the y-axis into a fixed unit size, e.g., GB or kB/s. When I see memory in "kB * 1e8" I have to do quite some mental gymnastics to realise that 0.2 = 20GB.

BTW, I like a lot plotting the time in relative seconds instead of the actual GMT clock time - much more useful.

**Comment by amete** [comment]
Thanks @graeme-a-stewart. I guess we can easily pass a multiplier (for both x and y axes) or allow the user to choose from a list of possible options (kb, mb, gb etc.). Prior gives more freedom but makes it a bit cumbersome to decide what units we should write to the label while the latter is more restrictive but eases the second issue. I believe the mainline usage would be just to convert either memory/data-transfer or time from the default units to more meaningful ones (i.e. kb2gb and sec2min). So, perhaps the second option would suffice?

**Comment by amete** [comment]
I just implemented and push the updated script that allows the user to change the units of the x/y-axes. The usage is like:

`./prmon_plot.py --xunit MIN --yunit GB`:
![prmon_wtime_vs_pss](https://user-images.githubusercontent.com/7428938/41050199-f9d2a08c-69b2-11e8-9528-bacc079d511b.png)


`./prmon_plot.py --xunit MIN --yunit GB --diff`:
![prmon_wtime_vs_diff_pss](https://user-images.githubusercontent.com/7428938/41050218-06583ec0-69b3-11e8-9703-278da1c149a9.png)

I can add a further protection that checks the consistency between the variable and the unit, i.e. throw and error if one tries `--xvar pss --xunit SEC` etc. but I'm not super sure if this is really necessary, maybe I'm being over cautious?

-s

**Comment by sciaba** [comment]
I am in favour of letting the user to choose the unit (any default is fine if the user can override it).
I was wondering if we can just get rid of " obtained from PrMon output", it makes the title unnecessarily long.

**Comment by amete** [comment]
Sure, I can strip that part to make the title short. Do we want to mention PrMon in some part of the plot?

**Comment by sciaba** [comment]
I don't see the need, personally.

**Comment by amete** [comment]
Cool, I just pushed the changes w/ the shortened title.

**Comment by graeme-a-stewart** [comment]
Fixed with #66
