### ISSUE TITLE
Lack of platform name handled badly

### ISSUE THREAD

**Issue by graeme-a-stewart** [HSF/prmon#69]
Trying to compile prmon on a gentoo linux system (part of the HSF Packaging group's test drive) I got this error:

```
CMake Error at cmake/prmonCPack.cmake:93 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.
Call Stack (most recent call first):
  cmake/prmonCPack.cmake:136 (hsf_get_platform)
  CMakeLists.txt:69 (include)
```

This seems to come from an empty/undefined value for `HSF_OS_VERSION`.

So this should be handled better for sure.

(There might well be an upstream issue for the HSF package template creator.)

**Comment by amete** [comment]
Fixed in #75, closing.
