### ISSUE TITLE
The prmon version in cmake configuration doesn't match the latest tag

### ISSUE THREAD

**Issue by amete** [HSF/prmon#71]
I noticed that the version that we just tagged (v1.0.0) and what we have in the main cmake configuration file are out of sync:

https://github.com/HSF/prmon/blob/16dc9cc89cdc0225819402f572ad0593cac24303/CMakeLists.txt#L7

We should probably fix this for the next tag.

**Comment by graeme-a-stewart** [comment]
I would suggest we accept #75 then update the version number to 1.0.1 and tag a new release.

**Comment by amete** [comment]
I fast-forwarded `stable` to `master` and released a new tag `v1.0.1` :) Closing this one, thanks a lot @graeme-a-stewart !
