### ISSUE TITLE
Both rchar and read_bytes get the label I/O Read (likewise for writes)

### ISSUE THREAD

**Issue by sciaba** [HSF/prmon#72]
The I/O plots don't differentiate from rchar and read_bytes apart from the color... The legend has to be fixed:

![prmon_wtime_vs_rchar_wchar_read_bytes_write_bytes](https://user-images.githubusercontent.com/12764525/41281244-2df03c58-6e31-11e8-9359-f6274b85f4a0.png)

Cheers,
Andrea

**Comment by amete** [comment]
Hi Andrea,

Thanks for reporting. That's an easy fix. These guys are all in `bytes`, I think right now we don't do the conversion for the `rchar` and `wchar` correctly, either. Will fix it asap.

-s
