### ISSUE TITLE
#processes and #threads and CPU efficiency

### ISSUE THREAD

**Issue by sciaba** [HSF/prmon#78]
Would it be possible to add two metrics: no. of processes in the process tree and no. of threads?
These numbers may vary over the lifetime of the monitored process, so it is interesting to track them.
Another interesting metric is the CPU efficiency over time. There are two options here:
1) calculate the average CPU efficiency from the start (less interesting)
2) calculate the instantaneous CPU efficiency (that is, averaged over a suitably small time interval).
The second option is a bit more complicated because one needs to calculate the increments in utime, stime and wtime over the previous time interval. Moreover, wtime must be multiplied by the total number of processes and threads, which also varies.
Thanks,
Andrea

**Comment by graeme-a-stewart** [comment]
Hi @sciaba 

Yes, let me have a think about that. I suppose you envisage that the efficiency would be (cpu consumption) / (sum of threads across processes)?

That could be misleading when there are more threads running than their are cores (whether real or HT) or when processes start or end close to a snapshot time, so don't run for the entire interval.

With those caveats it's quite possible to do this though.

Graeme

**Comment by amete** [comment]
Hi guys,

I think tracking the number of processes and threads that are being listened to at each sampling point is a good idea and should be fairly easy.

As for the efficiency, I would personally refrain from putting in complex/derived information into the output as much as possible. In principle, we already have enough information to derive cpu utilization information a la (i.e. from plotting):

![cpu-utilization](https://github.com/HSF/prmon/blob/c87de848d11cc4f77f39505e5b0d84a8c0e40514/example-plots/PrMon_wtime_vs_diff_utime_stime.png)

In the most basic form, the efficiency (well one way to define it at least) would be the above plot divided by nproc*nthreads (apart from more threads than cores point Graeme mentioned above).

Best,
Serhan

**Comment by sciaba** [comment]
Hi,
I agree that we can leave the CPU efficiency out and leave to the user the burden of building derived metrics, in particular when they could be misleading... So having #processes and #threads as simple metrics would be quite enough.
Cheers,
Andrea

**Comment by amete** [comment]
Hi guys,

I think we can count the number of processes in the `pids` loops, i.e. for [cpumon](https://github.com/HSF/prmon/blob/3b2783d588c308fa41e52a1c5033ede40fc8ddbb/package/src/cpumon.cpp#L25). There we also open the `/proc/pid/stat` file in which the 20th entry is the number of threads [1](http://man7.org/linux/man-pages/man5/proc.5.html). We can also sum these up to report the aggregated values. Does that make sense @graeme-a-stewart ?

Best,
Serhan

**Comment by graeme-a-stewart** [comment]
So with #90 accepted I think this is done
