### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by graeme-a-stewart** [HSF/prmon#79]
We should setup Travis to run some CI jobs for `prmon`.

Start with one platform (like Ubuntu16) and then add some others once that works.

**Comment by graeme-a-stewart** [comment]
Merged #80 to get this going...

**Comment by graeme-a-stewart** [comment]
OK, the CI is running now, but I realised that Travis changed their setup from that used by the HSF website. From [the logs](https://travis-ci.com/HSF/prmon/builds/82028344) it seems that the container was pulled properly, but that maybe it needs to be started manually now as the gcc7 compilers were not found by CMake, but they are in the container.

**Comment by graeme-a-stewart** [comment]
Doh! Of course, you always need to start the container yourself. This is now fixed and the CI build on Ubuntu 16 works.

**Comment by graeme-a-stewart** [comment]
Build tests now work correctly. Builds were initially enabled for both branches and pull requests. For now I disabled them for branches. Developers should run their own tests during development and the automated ones can run once a PR has been made.

**Comment by amete** [comment]
Fixed in #82, closing.
