### ISSUE TITLE
Consider use of nlohmann/json code

### ISSUE THREAD

**Issue by graeme-a-stewart** [HSF/prmon#88]
There was some discussion on ATLAS lists that concluded that people favoured [Niels Lohmann's JSON code for C++](https://github.com/nlohmann/json). It's a header only library that can actually be made as concise as a single (albeit large) file to be included. 

It would be good to evaluate that as an alternative to RapidJSON, especially if it could be provided easily bundled with prmon.

**Comment by amete** [comment]
Hi @graeme-a-stewart,

I just pushed a prototype for using `nlohmann/json` in favor of `RapidJSON` under `master-new-json-parser`. I didn't make any changes in the way we do things apart from making it work w/ the new library. I can also create a PR if you think it's better to have the discussion under that. Please let me know what you think. 

Best,
Serhan
