### ISSUE TITLE
Monitoring frequency?

### ISSUE THREAD

**Issue by sciaba** [HSF/prmon#97]
Would it be feasible to add the possibility to monitor the frequency of the cores on which the application is running, or of all the cores on the system (easier and probably more sensible)?
A simple

cat /proc/cpuinfo | grep MHz

shows in real time the actual frequency of each core. This would allow to find out if the CPU was using a turbo frequency or was throttling at any point during the execution of the application.

Cheers,
Andrea

**Comment by amete** [comment]
Hi @sciaba,

The only issue that I foresee here is that we need to somehow now the proc/thread <-> CPU association. This would need some extra bookkeeping which might be a bit convoluted. We can simply dump the /proc/cpuinfo but then we don't really know if the scaling potentially affect the process that we're listening. We also probably need to store the baseline frequency (min/max) of the processor to judge how much scaling is going one. I'll give this some thought but please let me know if you have any suggestions. Also let me tag @graeme-a-stewart in case he has an idea.

Many thanks.

Best,
Serhan

**Comment by sciaba** [comment]
Ideally what you say is correct, but I think it would be acceptable just to record the absolute clock speed of each core in the system. This is what any motherboard monitor tool would do, it's not imperative to identify the cores used by the process(es), also because they may well change over time and the time charts would be difficult to interpret. A first implementation along these lines should be trivial and would allow users to understand if it's sufficient.

Cheers,
Andrea

**Comment by amete** [comment]
Thanks Andrea. If we're only after the information whether or not scaling is enabled, I think there is a neater solution. On Linux CPUfreq exposes CPU information here:

`/sys/devices/system/cpu/cpu{CPUID}/cpufreq/scaling_governor`

where the `CPUID` is essentially the index in 0...Nprocessors-1. The scaling is off if this reads `performance` and on otherwise (in most recent versions the only other option is `powersave`). We can read this over all CPUs and store a single column w/ a boolean in the text file for each measurement. Would this suffice you think?

-s

**Comment by sciaba** [comment]
Hi Serhan,
I would still like to see a clock frequency... maybe you are right, but the clock frequency would allow e.g. to compare plots obtained on different CPUs which may have different base and boost clock frequencies.

Cheers,
Andrea

**Comment by amete** [comment]
Hi @graeme-a-stewart,

Apparently I took a stab at this in #102 but we didn't resolve it. How would you like to proceed? Please let me know, many thanks.

Best,
Serhan

**Comment by graeme-a-stewart** [comment]
Yes, I woke up - let me take a look.

One issue, which we also discussed in SPOT, is that we don't record anywhere the CPU types (or GPU types, now that that becomes a thing). So maybe we should have them somewhere in a log file.

**Comment by amete** [comment]
For the hardware information, I was thinking about creating a new section in the JSON and putting it there but of course we can do it in some other way. 

By the way, let me ping @sciaba  just to see if he's still interested in getting the clock freq.s in the `prmon` output.

**Comment by graeme-a-stewart** [comment]
Yeah, that's a pretty good place to put it (I had been thinking an extra logfile, but the JSON is much more usable). How about a new key "hw"? Then we can collect things there, if people like the idea (option switch?).

**Comment by graeme-a-stewart** [comment]
See comments on #102 - overall I am not convinced this is very useful.

**Comment by graeme-a-stewart** [comment]
So the consensus in the end was not to implement this
