### ISSUE TITLE
"Smart" compression of prmon data

### ISSUE THREAD

**Issue by sciaba** [HSF/prmon#99]
It would be good to implement a method to reduce the size of the prmon output by discarding "useless" data; for example, if a metric is linear between two points, there is no reason to keep the intermediate values. For metrics with a linear behaviour across large time intervals, this may reduce the data generated by 2 orders of magnitude or more. The algorithm I'm proposing is demonstrated at

https://cernbox.cern.ch/index.php/s/lKZgVgk2Fhwl3f6

This compression should not be the default but it should be enabled by command line options and needs a "precision" parameter with a sensible default (I propose 10% of the difference between max and min of the metric).

**Comment by sciaba** [comment]
Hi Serhan,
do you think that this algorithm could be implemented directly in PrMon?
Cheers,
Andrea

**Comment by rmaganza** [comment]
Hello, 
I just wanted to add that I have tested Andrea's proposed algorithm - I think the original link is now dead but he is going to update it soon - on some long ATLAS monitored jobs (10+ h)  and, while very simple, it manages to achieve big compression rates of up to 98% with minimal information loss.

It could thus be very helpful to implement directly in prmon as a possible solution that can help with longer term storage of the original time series. Good to know that you added this to the next milestone.

Regards,
Riccardo

**Comment by amete** [comment]
We can finally close this 👍 The functionality should be in the newest release:
 
https://github.com/HSF/prmon/releases/tag/v2.2.0

Please let us know your feedback @sciaba and thanks @rmaganza for the implementation.
